### ISSUE TITLE
Plugin breaks `yarn/npm run serve`

### ISSUE THREAD

**Issue by mrksbnch** [Akryum/vue-cli-plugin-ssr#10]
I'm aware that this plugin is supposed to add SSR to a Vue CLI project and `yarn/npm run ssr:serve` works fine but it would still be great to support `yarn/npm run serve` in order to run the project as a regular SPA without SSR (if needed).

Currently, after adding this plugin and trying to run the development server (without SSR) it just shows a blank page. The other SSR plugin (https://github.com/vueneue/vueneue) seems to support both npm commands.

**Comment by Akryum** [comment]
Fixed in https://github.com/Akryum/vue-cli-plugin-ssr/commit/459896f5ae0dc4f71d59026d34a1e47dee3f8542
