### ISSUE TITLE
No way to process Internal Server Error (500)

### ISSUE THREAD

**Issue by yekver** [Akryum/vue-cli-plugin-ssr#11]
I want to create custom template for 500 page error, but according to [this piece of code](https://github.com/Akryum/vue-cli-plugin-ssr/blob/master/lib/app.js#L89-L91) there is no way to handle this error in SPA and return beautiful page, isn't it?

**Comment by maviola5** [comment]
I wanted to piggy back on this request. I have a need for "hard" 404 errors. This could also pair well with the pull request for middleware (https://github.com/Akryum/vue-cli-plugin-ssr/pull/23) and give the ability for a multi-page application via middleware option. I submitted a pull request for consideration: https://github.com/Akryum/vue-cli-plugin-ssr/pull/29
