### ISSUE TITLE
Error: Content placeholder not found in template.

### ISSUE THREAD

**Issue by yekver** [Akryum/vue-cli-plugin-ssr#13]
Comment `<!--vue-ssr-outlet-->` is deleted in production build and SSR is not working. This can be fixed by renaming file `index.html` back to `index.template.html`.

**Comment by sneko** [comment]
@Akryum @yekver I'm using the version 0.3 and I'm having this issue even by renaming it to `index.template.html`.

Maybe I'm doing something wrong... Firstly I'm building the project and then serving it like that:
```
cross-env NODE_ENV=production vue-cli-service ssr:build
cross-env NODE_ENV=production vue-cli-service ssr:serve
``` 

And that's when serving I get the error `Error: Content placeholder not found in template.`. When looking inside the `dist/index.html` there is no `<!--vue-ssr-outlet-->`.

I could first build as `NODE_ENV=development` and then serve as `NODE_ENV=production` but it doesn't make sense this the source code is not minified when reaching it in my browser.

Do you have an idea what could be the origin of this 🤔 ?

Thank you,

**Comment by sneko** [comment]
Unfortunately I'm still stuck with this issue 😢 

I'm trying to debug step by step to see what's going wrong...

**Comment by sneko** [comment]
https://github.com/Akryum/vue-cli-plugin-ssr/blob/master/lib/webpack.js#L14
https://github.com/Akryum/vue-cli-plugin-ssr/blob/v0.3.0/lib/webpack.js#L14

I guess that's because the condition is about the mode and not the `process.env.NODE_ENV`. In my case I use "dev/prod" as mode since I had 1 year ago conflicts to run PWA properly in both mode with Vue.js.

**Comment by hmillison** [comment]
This is still an issue if you have multiple modes that need the production build (for multiple environment), it would be preferable to switch to detecting the `isProd` flag via NODE_ENV instead of mode.
