### ISSUE TITLE
Wrong cached response without query params

### ISSUE THREAD

**Issue by prog666** [Akryum/vue-cli-plugin-ssr#17]
When rendering page which can have query params if has cached with some params, but page was requested with no query at all it returns wrong cached page. I guess it is not problem with your problem, i just cant make an issue for vue-server-renderer =(. Maybe we can find a way to fix this together.

**Comment by prog666** [comment]
so now i removed cache option completely, but i still get this issue..

**Comment by prog666** [comment]
okay, so now i found the problem. Vuex on server preserves state between requests. That's wierd

**Comment by zickat** [comment]
instead of state: {}, you can do like data in components: 
```javascript
state: () => ({})
```

**Comment by prog666** [comment]
i've done this to my vuex module

```
export default {
  namespaced: true,
  state: () => initialState,
  getters,
  actions,
  mutations,
};
```

it didn't help

**Comment by Akryum** [comment]
You are still not creating a new object for each store instance. `initialState` is just returned, so it will be reused accross requests.

**Comment by prog666** [comment]
Thanks!
