### ISSUE TITLE
Change location of generated entry files

### ISSUE THREAD

**Issue by ramsaylanier** [Akryum/vue-cli-plugin-ssr#2]
Is it possible to change the location of where the client and server entry files are located? Currently `yarn run ssr:serve` looks for them in the root `src` directory, but I'd like mine elsewhere. Perhaps this can be configurable in the `vue.config.js` file?

**Comment by Akryum** [comment]
In `vue.config.js`:

```js
module.export = {
  pluginOptions: {
    ssr: {
      entry: target => `./src/entry-${target}`,
    }
  }
}
```
