### ISSUE TITLE
Don't cache service-worker.js when using pwa plugin

### ISSUE THREAD

**Issue by Narkoleptika** [Akryum/vue-cli-plugin-ssr#22]
Hello, thanks for this and the apollo plugins! Just a real quick change here.

I'm using this plugin along with the pwa plugin and am receiving the following warning on Chrome 69.0.3497.92

![screenshot from 2018-09-15 22-26-33](https://user-images.githubusercontent.com/7088166/45593242-aa387780-b936-11e8-932c-85797fa891d8.png)

The last argument to serve needs to either be omitted or changed to false on the following line: https://github.com/Akryum/vue-cli-plugin-ssr/blob/master/lib/app.js#L80

Thanks!

**Comment by mrksbnch** [comment]
@Akryum As this should probably be fixed and is an easy change (https://github.com/Akryum/vue-cli-plugin-ssr/blob/master/lib/app.js#L83), would you accept a MR for this?
