### ISSUE TITLE
CSS being rendered as style tag on build

### ISSUE THREAD

**Issue by milad-alizadeh** [Akryum/vue-cli-plugin-ssr#36]
Everything works so great with this plugin! I just had a small question. When I run `ssr:build` all the css files inside my `<style>`  tags are being rendered on the html as style tag and I also have them referenced as `main.css`. Is there a way to remove the style tag from the outputted html?

Here's the outputted html.
<img width="1306" alt="screenshot 2018-11-15 at 17 05 57" src="https://user-images.githubusercontent.com/9379343/48569084-d0f43980-e8f8-11e8-82dc-5c06f8074746.png">

and here is my `App.vue`
```
<template>
  <div id="app">WebApp</div>
</template>

<script>
export default {
}
</script>

<style lang="scss">
  body {
    background: red;
  }
</style>

```

**Comment by dehypnosis** [comment]
Same issue here

**Comment by Akryum** [comment]
This is not a bug but a feature called Critical CSS injection.

**Comment by Spittal** [comment]
We have also observed that the critical CSS it is not being run through our PostCSS configuration, leaving CSS variables in place and other non standard PostCSS features.

**Comment by Spittal** [comment]
Hey @Akryum, I did several tests and I see that the only issue is minification and the stripping of comments in the CSS.

My problem previously was that I was using `postcss-smart-import` which is unmaintained. I switched to `postcss-import`. Thanks.
