### ISSUE TITLE
How to run the plugin with npm

### ISSUE THREAD

**Issue by oluwajubelo1** [Akryum/vue-cli-plugin-ssr#4]
Can't i run the plugin using npm? Must it only be yarn run ssr:serve. Thanks

**Comment by Akryum** [comment]
Well use `npm run ssr:serve`.

**Comment by oluwajubelo1** [comment]
After i successfully installed vue add @akryum/ssr , i got this error : Error: Cannot find module '@vue/cli-shared-utils'. I'm using vue-cli 3 rc2. So, running npm run ssr:serve gave the this error: "npm ERR! missing script: ssr:dev". Thanks for helping out
