### ISSUE TITLE
How to serve in production ?

### ISSUE THREAD

**Issue by darkiron** [Akryum/vue-cli-plugin-ssr#44]
Hi,
How to serve my app with PM2 manager and express ?

**Comment by Akryum** [comment]
Run `ssr:build` and then to start the express server run `ssr:start`. There is also a connect middleware that can be used like this:

```js
import ssrMiddleware from '@akryum/vue-cli-plugin-ssr/lib/app'

module.exports = app => {
  ssrMiddleware(app, { prodOnly: true })
}
```

**Comment by darkiron** [comment]
with PM2 ?

**Comment by darkiron** [comment]
thanks, it's great new form me !
