### ISSUE TITLE
Does not work out of the box

### ISSUE THREAD

**Issue by khejit** [Akryum/vue-cli-plugin-ssr#50]
Basically when I create fresh project with vue-cli, install pwa plugin, apollo plugin and ssr plugin, I expect that after yarn serve something will be visible for me in the front end. Instead I'm greeted with
`{{{ renderResourceHints() }}} {{{ renderStyles() }}} {{{ renderState() }}} {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}} {{{ renderScripts() }}}`
in my html and there's an error saying that #app element could not be found. Indeed there is no such element in public/index.html.
Do I need to follow additional setup steps? Why can't this vue-cli scaffolding work out of the box and present me some demo?

**Comment by Akryum** [comment]
The right command is `ssr:serve`. SPA-only mode isn't working yet.

**Comment by jamiecarter7** [comment]
Any idea when SPA-mode might be ready?
