### ISSUE TITLE
how to use asyncData ?

### ISSUE THREAD

**Issue by mesutgok** [Akryum/vue-cli-plugin-ssr#51]
Hi, 

how to use asyncData ? I have problem app init vuex state data.

Good works 

```
 App running at:
  - Local:   http://localhost:8001
(node:10829) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'errorMessage' of undefined
    at app.js:3606:20
(node:10829) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). (rejection id: 716)
```

**Comment by p1n5u** [comment]
Can you provide a demo repo or a sandbox with your code in it? With a simple log message, it is difficult to point out the issue. 

Thanks

**Comment by hmillison** [comment]
Does this library support an `asyncData` method in Vuex or Vue? I don't see any references to it in the code or the docs?

**Comment by p1n5u** [comment]
The ‘asyncData‘ hook is only needed for vue <=2.5 and is not natively supported. You can refer to the vue ssr guide so see how to implement it.
If you use vue 2.6 or greater you can use the ‘serverPrefetch‘ hook which is natively supported for prefetching data. https://ssr.vuejs.org/guide/data.html#logic-collocation-with-components

**Comment by hmillison** [comment]
thanks @p1n5u. I had been trying to use `serverPrefetch`, but it wasn't working due to an issue from another library.

**Comment by p1n5u** [comment]
@hmillison could you make a repo with your code? I would like to take a closer look at the issue you have 🙂

**Comment by hmillison** [comment]
Im using this library with vue-class-component, which has not added “serverPrefetch” to their list of component hooks: https://github.com/vuejs/vue-class-component/pull/312

**Comment by mesutgok** [comment]
@p1n5u @hmillison vue cli ssr plugin and axios data fetch ssr using repo share pls ? I have problem api call vuex inital state not update

**Comment by ilajosmanov** [comment]
> The `asyncData` hook is only needed for vue <=2.5 and is not natively supported. You can refer to the vue ssr guide so see how to implement it.
> If you use vue 2.6 or greater you can use the `serverPrefetch` hook which is natively supported for prefetching data on the server side. https://ssr.vuejs.org/guide/data.html#logic-collocation-with-components

Do you created `prefetch` mixin?

**Comment by Igor-Golovtsov** [comment]
@mesutgok hi, try use serverPrefetch for data fetch
```js
serverPrefetch() {
  return this.fetchUsers();
},
methods: {
  fetchUsers() {
    return this.$store.dispatch('getUsers');
  },
}
```
