### ISSUE TITLE
HMR doesn't apply to the DOM

### ISSUE THREAD

**Issue by houd1ni** [Akryum/vue-cli-plugin-ssr#7]
Thank you for the most accurate ssr plugin at first :)

I do:
vue add `this plugin`
yarn ssr:serve

browser console:

```
[HMR] connected client.js:92
// then I've made changes in App.vue, i.e.
[HMR] bundle rebuilding client.js:234
[HMR] bundle rebuilt in 1756ms client.js:242
[HMR] Checking for updates on the server... process-update.js:41
[HMR] Updated modules: process-update.js:114
[HMR]  - ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/home/ ... src/App.vue?vue&type=template&id=7ba5bd90& process-update.js:116
[HMR]  - ./src/App.vue?vue&type=template&id=7ba5bd90& process-update.js:116
[HMR] App is up to date. process-update.js:121 
```
And it doesn't affect DOM: I cannot see the changes.

Version: the latest vue-cli to now and webpack.

**Comment by Akryum** [comment]
Can't reproduce on upcoming version.

**Comment by houd1ni** [comment]
Template rewriter probably does not work with typescript and I eventually had to put before and afterApp to my main**.ts** It's OK now.
