### ISSUE TITLE
Guidance on running this project locally

### ISSUE THREAD

**Issue by hmillison** [Akryum/vue-cli-plugin-ssr#79]
Hi, i'm trying to run this project locally with it linked to my own application so I can test out some minor updates to this, but I am getting a number of "cannot find module" errors when running `npm run ssr:serve`.

Any guidance on specific configuration that is needed to run this locally?

**Comment by Akryum** [comment]
Replace the version with `file:../path/to/ssr-plugin` in `package.json` instead of using `yarn link` and use `yarn --force` to update it when you make changes.

**Comment by hmillison** [comment]
got it! that must be what i was missing.

**Comment by hmillison** [comment]
thanks! that did the trick
