### ISSUE TITLE
How do you set a custom title?

### ISSUE THREAD

**Issue by prog666** [Akryum/vue-cli-plugin-ssr#9]
I found that you take it from config as defaultTitle, but how do i change it in code, not in template?

**Comment by zickat** [comment]
In tour entry server, you can change the title doing : 
```javascript
context.title = 'A new title';
```

**Comment by prog666** [comment]
thanks!

**Comment by phil294** [comment]
For anyone still looking for this, you should probably just use the official recommended way of doing it: https://ssr.vuejs.org/guide/head.html
